# Generated by Django 5.1.5 on 2025-01-28 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
