# Generated by Django 5.1.5 on 2025-02-05 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_remove_product_image1_remove_product_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
