# Generated by Django 5.1.5 on 2025-02-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='offer_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage for all products under this brand.'),
        ),
        migrations.AddField(
            model_name='category',
            name='offer_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage for all products under this category.'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage for this product.'),
        ),
    ]
