# Generated by Django 5.1.5 on 2025-02-27 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_brand_offer_percentage_category_offer_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='offer_percentage',
        ),
    ]
