# Generated by Django 5.1.5 on 2025-02-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_remove_category_offer_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='offer_percentage',
        ),
    ]
