# Generated by Django 5.1.5 on 2025-03-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_remove_brand_offer_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='offer_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage for this brand.'),
        ),
    ]
