# Generated by Django 5.1.5 on 2025-03-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_brand_offer_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
