# Generated by Django 5.1.5 on 2025-03-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='Brand_image',
            field=models.ImageField(blank=True, null=True, upload_to='Brand_images/'),
        ),
    ]
