# Generated by Django 5.1.5 on 2025-03-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_brand_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='Brand_image',
            field=models.ImageField(blank=True, null=True, upload_to='brand_images/'),
        ),
    ]
