# Generated by Django 6.0.6 on 2026-06-19 14:46
# Hand-edited: reordered operations so data migration runs BEFORE old columns are dropped.

import django.db.models.deletion
from django.db import migrations, models


def migrate_variant_data_forward(apps, schema_editor):
    """
    Copy old ProductVariant data into the new normalised structure:
      - color  → VariantAttribute(attribute_name='color')
      - image1 … image4 → VariantImage rows (sort_order 1..4)
      - name   = old color value (used as the display name)
    """
    ProductVariant  = apps.get_model('Products', 'ProductVariant')
    VariantAttribute = apps.get_model('Products', 'VariantAttribute')
    VariantImage    = apps.get_model('Products', 'VariantImage')

    for variant in ProductVariant.objects.all():
        # ── name (display label) ──────────────────────────────────────
        old_color = getattr(variant, 'color', '') or 'Unnamed Variant'
        variant.name = old_color
        variant.save(update_fields=['name'])

        # ── VariantAttribute: color ───────────────────────────────────
        if old_color and old_color != 'Unnamed Variant':
            VariantAttribute.objects.get_or_create(
                variant=variant,
                attribute_name='color',
                defaults={'attribute_value': old_color},
            )

        # ── VariantImage: promote image1 … image4 ────────────────────
        for sort_order, field_name in enumerate(['image1', 'image2', 'image3', 'image4'], start=1):
            image_value = getattr(variant, field_name, None)
            if image_value:
                VariantImage.objects.create(
                    variant=variant,
                    image=image_value,
                    sort_order=sort_order,
                    alt_text=f"{old_color} – view {sort_order}",
                )


def migrate_variant_data_backward(apps, schema_editor):
    """
    Reverse: restore color from VariantAttribute, image1-4 from VariantImage.
    Best-effort only — data beyond 4 images is lost on reversal.
    """
    ProductVariant  = apps.get_model('Products', 'ProductVariant')
    VariantAttribute = apps.get_model('Products', 'VariantAttribute')
    VariantImage    = apps.get_model('Products', 'VariantImage')

    for variant in ProductVariant.objects.all():
        # Restore color
        color_attr = VariantAttribute.objects.filter(
            variant=variant, attribute_name='color'
        ).first()
        if color_attr:
            variant.color = color_attr.attribute_value
            variant.save(update_fields=['color'])

        # Restore images (up to 4)
        for img_obj in VariantImage.objects.filter(variant=variant).order_by('sort_order')[:4]:
            field_name = f'image{img_obj.sort_order}'
            setattr(variant, field_name, img_obj.image)
        variant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_alter_brand_brand_image'),
    ]

    operations = [
        # ── Step 1: Add new fields to existing tables ────────────────────────
        migrations.AddField(
            model_name='brand',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='offer_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage applied to all products in this category.'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='name',
            field=models.CharField(default='Unnamed Variant', help_text="Human-readable display name, e.g. 'Midnight Black – 42mm Leather'.", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='offer_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage applied to all products of this brand.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Product-level discount percentage.'),
        ),

        # ── Step 2: Create the new normalised tables ─────────────────────────
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='variant_images/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Products.productvariant')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=100)),
                ('attribute_value', models.CharField(max_length=255)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='Products.productvariant')),
            ],
            options={
                'ordering': ['attribute_name'],
                'unique_together': {('variant', 'attribute_name')},
            },
        ),

        # ── Step 3: DATA MIGRATION — rescue existing data before columns drop ─
        migrations.RunPython(
            migrate_variant_data_forward,
            reverse_code=migrate_variant_data_backward,
        ),

        # ── Step 4: Drop the old columns (data is safe in new tables now) ─────
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='image4',
        ),
    ]
