# Generated by Django 6.0.6 on 2026-06-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_remove_productvariant_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='applied_offer',
            field=models.PositiveIntegerField(default=0, help_text='applied discount percentage.'),
        ),
    ]
