# Generated by Django 5.1.5 on 2025-02-15 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0007_order_razorpay_order_id_order_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_completed',
        ),
    ]
