# Generated by Django 5.1.5 on 2025-02-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0011_order_is_returned_alter_orderstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('refund_pending', 'Refund Pending'), ('refund_completed', 'Refund Completed'), ('refund_not_required', 'Refund Not Required'), ('payment_not_received', 'Payment Not Received')], default='pending', max_length=50),
        ),
    ]
