# Generated by Django 5.1.5 on 2025-02-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0015_order_applied_coupon_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
