# Generated by Django 5.1.5 on 2025-02-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0016_order_shipping_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_status',
            field=models.CharField(choices=[('no_request', 'No Request'), ('requested', 'Return Requested'), ('approved', 'Return Approved'), ('rejected', 'Return Rejected')], default='no_request', max_length=50),
        ),
    ]
