# Generated by Django 5.1.5 on 2025-03-05 15:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0018_productreview'),
        ('Products', '0010_brand_offer_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('user', 'product')},
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='order_item',
        ),
    ]
