# Generated by Django 6.0.6 on 2026-06-19 14:46
# Hand-edited: added RunPython to backfill unit_price_at_purchase for existing OrderItem rows.

from django.db import migrations, models
from decimal import Decimal


def backfill_order_item_prices(apps, schema_editor):
    """
    Populate unit_price_at_purchase and discount_applied for all existing
    OrderItem rows, using the current product sales_price and offer as a
    best-effort snapshot (actual purchase price is unknown for old rows).
    """
    OrderItem = apps.get_model('Cart', 'OrderItem')

    for item in OrderItem.objects.select_related(
        'product_variant__product__brand',
        'product_variant__product__category',
    ).all():
        product = item.product_variant.product

        # Use sales_price if available, otherwise fall back to regular_price
        price = product.sales_price if product.sales_price else product.regular_price
        item.unit_price_at_purchase = price if price else Decimal('0')

        # Best-effort: record the product-level offer percentage
        item.discount_applied = product.offer_percentage or 0

        item.save(update_fields=['unit_price_at_purchase', 'discount_applied'])


def reverse_backfill(apps, schema_editor):
    """Reversal is a no-op — resetting to 0 is fine since the fields are being removed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0019_alter_productreview_unique_together_and_more'),
    ]

    operations = [
        # Add the new snapshot columns first
        migrations.AddField(
            model_name='orderitem',
            name='discount_applied',
            field=models.PositiveIntegerField(default=0, help_text='Offer % that was active when order was placed.'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price_at_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),

        # Then backfill existing rows with the current product price as a snapshot
        migrations.RunPython(
            backfill_order_item_prices,
            reverse_code=reverse_backfill,
        ),
    ]
