# Generated by Django 5.1.5 on 2025-02-27 06:23

import admin_home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0005_alter_coupon_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[admin_home.models.validate_discount_percentage]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_cart_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[admin_home.models.validate_min_cart_value]),
        ),
    ]
