# Generated by Django 6.0.6 on 2026-06-27 14:53

import admin_home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0006_remove_coupon_discount_coupon_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional cap on the discount. E.g. 50% coupon capped at ₹200 max.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage off the cart subtotal.', max_digits=5, validators=[admin_home.models.validate_discount_percentage]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_cart_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum cart subtotal required to use this coupon.', max_digits=10, validators=[admin_home.models.validate_min_cart_value]),
        ),
    ]
