# Generated by Django 5.1.5 on 2025-01-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0002_remove_address_addres_type_address_address_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
